device: 'cuda'
random_seed: 1234 # updated by run scripts
folder_location: './results/'
folder_name: 'test' # updated by run scripts
resume: False
minibatch_size: 128
drop_smaller_than_minibatch: True
sided_Q: 'negative'  #Can be 'positive' or 'negative'
perception_neg_traj_ratio: 'NA'

state_dim: 2          
# 'stringency_index', 'new_cases'                      
num_actions: 5  
#  face coverings     
context_dim: 8                     
# Number of context/demographic/binary indicator variables we'll use as input
# 'population_density', 'gdp_per_capita', 'diabetes_prevalence','cardiovasc_death_rate', 'aged_65_older', 'human_development_index','life_expectancy', 'hospital_beds_per_thousand'

# update these manually
storage_path: 'C:/Users/pabgon/rl_representations/srl_test/'

train_data_file: './data/rewards_new_cases/gap_5/train_set_tuples'
#train_data_file: './data/rewards_new_cases/gap_14/train_set_tuples'

validation_data_file: '/scratch/hdd001/projects/ml4h/projects/srl_rl4h_tuples/new_val_set_tuples'
test_data_file: './data/rewards_new_cases/gap_5/test_set_tuples' 
#test_data_file: './data/rewards_new_cases/gap_14/test_set_tuples' 

behav_policy_file_wDemo: './behavcloning/test/new_cases_gap5/BC_model.pt'
behav_policy_file: './behavcloning/test/new_cases_gap5/BC_model.pt'


#### this file is for bcq with representation states